### PR TITLE
Is309 provider books client specific offerings

### PR DESCRIPTION
**Pull request by situatedbit**
This is a pull request for #309 into the #4 feature branch.

``app/source/html/activities/serviceProfessionalService.html``
``app/source/html/templates/service-professional-service.html``

- I moved the logic for displaying the services grouping label out of the templates and into the new objects for grouping services.

``app/source/js/activities/serviceProfessionalService.js``

- I load different services depending on what mode the services activity is in. Also, I choose a different service grouper algorithm depending on the mode.

``app/source/js/activities/serviceProfessionalService.js``
``app/source/js/viewmodels/ServiceProfessionalService.js``
``app/source/js/viewmodels/presenters/*``

- I refactored ``groupServices()`` substantially. This might be a little obtuse initially, but I think it will isolate cases into smaller bits of named configurations rather than having to trace logic.
- ``*Grouping`` objects provide labelling functions; they use ``*Grouper`` objects to group services
- ``*Grouper`` objects produce a presenter object that is added to the view model
- ``presenters/GroupedServicesPresenter.js``: the object added to the view model and rendered in templates
- ``presenters/ServicesGrouper.js``: grouping algorithm; label functions can be overwritten with options; creates group service presenter objects
- ``presenters/ClientSpecificServicesGrouper.js``: divides services into client-specific and public services, then uses ``ServicesGrouper``; 
- ``ClientBookingServicesGrouping.js``, ``ProviderBookingServicesGrouping.js``, ``ProviderManagingServicesGrouping.js``: These grouping objects provide configuration for the groupings for different use cases. They have label functions to override the default services grouping label.

### CODE REVIEW

**Comment by IagoSRL** [comment]
Please @situatedbit, review and resolve the conflicts that appeared on this because of other changes merged at is4.

**Comment by situatedbit** [comment]
I've resolved the conflicts, but didn't merge in case you wanted to look further.

**Comment by situatedbit** [comment]
Thanks, @IagoSRL. I think the branch can be merged before fixing the bug, but the bug should be fixed before the feature #4 is merged into master.

**Comment by IagoSRL** [comment]
@situatedbit As we commented, merging to move forward, but with the bug you know pending of fix at #4

**Comment by situatedbit** [comment]
Thanks

**Pull request merged**
