### PR TITLE
Updated favicon with accessible color

### PR DESCRIPTION
**Pull request by joshdanielson**
#581

### CODE REVIEW

**Comment by joshdanielson** [comment]
@IagoSRL not sure what more I need to do. Let me know.

**Comment by IagoSRL** [comment]
Nothing more. should be up with the release, but forgot update a file (I had to introduce cache-busting at web.config to "help" browsers to update the use of the favicon).

**Comment by IagoSRL** [comment]
It's uploaded, but favicons have reputation of not updating when you want, even forcing it in some way. Check if appears now the correct one (both dev and live)

**Comment by joshdanielson** [comment]
@IagoSRL it isn't loading yet but is blank so will check it again later today.

**Pull request merged**
