### PR TITLE
Update Backend Development Environment Setup Guide.md

### PR DESCRIPTION
**Pull request by situatedbit**
added notes about Windows authentication to connect to local database

### CODE REVIEW

**Comment by IagoSRL** [comment]
@situatedbit first PR like this I tagged/archived the branches just for process, but since names are reusing and not so important I will just delete the branch; it's OK?

**Comment by situatedbit** [comment]
Yes - it's ok.

**Comment by situatedbit** [comment]
I'm using the editor on Github for these small changes to documentation

**Comment by IagoSRL** [comment]
OK, that's why that name, got it.

**Pull request merged**
