### PR TITLE
Implement live region to provide screen reader feedback for password validation rules.

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by ndarilek** [comment]
I don't know if how you've done this is the best way, but this solution provides the following screen reader benefits:

 * When I initially enter a password, the unsatisfied requirements are spoken.
 * When all requirements are met, "You're set!" is spoken.

This might require additional UX testing, but I'd call this accessible in the sense that updates to the requirements are spoken as they change.

Suggested improvements:

 * Change the text "At least 8 characters long" to "Must be at least 8 characters long" so it becomes clear that a requirement, not a current condition, is being spoken.
 * Likewise, change the character kinds in a similar way to indicate that they are a requirement.

**Comment by IagoSRL** [comment]
I'm surprised that just that detail make it works, good to know! and thanks!

I like the recommendation for the new text. @joshdanielson has some comment about that (the amended text could be just for sr-only, but I think can be fine for all, what do you think?).

**Comment by IagoSRL** [comment]
I merged this since I'm OK, just left the question about amending the text for @joshdanielson and can do it directly on the branch.

**Comment by joshdanielson** [comment]
@ndarilek @IagoSRL just committed the change per @ndarilek 's suggestion. Much clearer now, thank you.

**Comment by IagoSRL** [comment]
I was doing some more testing with NVDA and Firefox on Windows, and the experience didn't 'sounds' good to me.
On my case, if I type text that meets one condition, it reads just the updated words, like '2 more' when the text "Includes at least 3 character types:" changes to "Includes at least 2 more character types:" and no reference to what condition was met and what left.

I suppose the experience may be different with other screen readers. What's you screen reader, browser, system Nolan?

The 'You are set' experience is perfect, though.

-----

Just thinking, may be this needs another 'div', blank at start, where to put text just for the screen reader with aria-live, and text specific to let them know what has changed and what's needed. I think the first is to think what we want to hear after user typed something that makes a condition to be met. Another thing, since the password field is before the requirements text, the user knows nothing in advance; NVDA is not reading that but seems other screen readers can read it as happened to @ndarilek. Not sure how to proceed with this.

**Comment by ndarilek** [comment]
I'm using Orca running under GNOME on Linux.

This touches on my usability concerns with this interface. I made this 
element as accessible as I know how, but in general it's a bit chatty. I 
generally don't set password requirements beyond a minimum length in my 
apps, so I don't immediately know how to easily make this complex list 
of requirements, with one embedded sublist, accessible in real-time.

A couple possibilities come to mind. First would be to simply require a 
"strong" password as defined by something like 
https://github.com/dropbox/zxcvbn (just what I found after a quick 
Google search.) Then you could simply fail on not having a strong 
password, with some text suggesting how to pick something good.

If that's a non-starter, you could revert my PR, concatenate the 
password requirements into a single string, then flash them with 
something like https://github.com/CodeSeven/toastr on form submission. 
But even then you'll get a long dump of text, which you'll need to 
slowly work through in order to meet all of these requirements.

Honestly I think you should just use a generic password strength metric 
instead of this (I.e. solution 1.) Your live region could then just be 
the text "weak" or "strong" with a requirement that a strong password be 
chosen.

**Pull request merged**
