### PR TITLE
Is430 Install FontAwesome v4.7.0

### PR DESCRIPTION
**Pull request by joshdanielson**
#430
-updated all FontAwesome files with 4.7.0

### CODE REVIEW

**Comment by IagoSRL** [comment]
I cannot accept this because it includes all the #191 changes too.

**Comment by IagoSRL** [comment]
It seems the only relevant commit for this PR here is https://github.com/loconomics/loconomics/pull/431/commits/100a7d9c7620095a40db1b78383234cfa96b3aa2

**Comment by joshdanielson** [comment]
@IagoSRL yes, that is the only commit. Sorry for merging it into this one.

**Comment by IagoSRL** [comment]
I had cherry picked the correct commit and applied on master, then I discard this pull request (even the purpose of this is done)

**Comment by joshdanielson** [comment]
@IagoSRL thanks!

**Pull request closed without merging**
