### PR TITLE
Add initial Travis configuration. Add an initial .travis.yml. This configuration should run the build task against the latest stable version of node. Ideally this should catch cases where the app won't build on a fresh checkout.

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by ndarilek** [comment]
Unfortunately, I can't finish this integration because I don't have access to modify this repository's hooks. But as we add more developers or work on increasingly complicated milestones, we're going to need something like this to catch situations that break master. So I got started and did the initial work to get this going.

**Comment by ndarilek** [comment]
This should be ready to merge.

**Comment by IagoSRL** [comment]
From my understanding, this depends on `yarn`, right?

Do you have which steps should be done to actually enable it in the repo?

**Comment by IagoSRL** [comment]
I just signedup at Travis and looked that seems enabled for Loconomics already :-O, don't know how it works without this set-up. Will merge

**Comment by ndarilek** [comment]
I just removed the yarn dependency. Sorry about that.

**Pull request merged**
