### PR TITLE
Is690 Revise addJobTitle accessibility

### PR DESCRIPTION
**Pull request by joshdanielson**
#690
- changed search result to singularName from pluralName
- added html form, fieldset, and legend tags

### CODE REVIEW

**Comment by joshdanielson** [comment]
@IagoSRL I added some minor changes under the epic-onboarding branch. I found a problem testing it (before I made my changes). Once I click "Create", it saves the job title but keeps me on the addJobTitle page:
screen shot 2017-10-27 at 9 36 17 am

**Comment by IagoSRL** [comment]
Will review. This branch has not the fix at master for the 'go back after save'; anyway, we must implement a different redirect here so it goes forward to listingEditor (when merged) rather than back.

**Comment by IagoSRL** [comment]
Actually, I will do the fieldset-legend change and text in label, I think is the correct in this case

**Comment by IagoSRL** [comment]
I did that change and I'm merging this.

Here before:
screenshot-2017-11-3 create a new listing - loconomics 1

After:
screenshot-2017-11-3 create a new listing - loconomics

**Comment by joshdanielson** [comment]
@IagoSRL looks good!

**Pull request merged**
