### PR TITLE
Switch package manager to Yarn Closes #755

### LINKED ISSUE #755: Evaluate switching to Yarn
Might be nice to consider switching package managers from NPM to [Yarn](https://yarnpkg.com). Advantages:

 * Much faster. Downloads in parallel, caches packages locally. Subsequent `yarn install` runs with a warm cache finish in seconds, or less.
 * More intelligent package resolution. I'm not sure #750 would have manifested under Yarn.
 * Nicer developer experience. Any binaries in node_modules/.bin can be run directly (I.e. with grunt-cli as a dependency, `yarn grunt atwork` runs Grunt directly without the user needing their own installation.)

I ran into some minor issues attempting this myself, but I'll sink half an hour or so putting together a PR for evaluation.

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by ndarilek** [comment]
No rush on merging this today, though I'd like to ask that it be considered, perhaps in parallel with #756. It also undoes #751 because that fix isn't necessary with Yarn, so in theory your Git reference should follow the harmony branch and doesn't need to be updated to a new commit.

**Comment by IagoSRL** [comment]
Found today that the actual problem with installing the package 'grunt-contrib-uglify' using npm and referencing a branch or commit, is that the project changed the package name internally, [three days ago](https://github.com/gruntjs/grunt-contrib-uglify/commit/ccb95a70cad6a4e9e902d3bd5d0e38a4de09a1e1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2), only at that branch, exactly at the commit updated at #750. Now is `grunt-contrig-uglify-es` (notice the '-es' at the end). That's too why didn't fail to me originally.

That's the source of the problem. Not even using the branch name as reference, but that they changed the name and we keep the previous formal name at package.json, so updating there fixes it. What I don't know now, is why yarn still updates if package names mismatch.
I think both package managers should notice the conflict of names, rather than work silently :-/

I committed that single line fix (just the name, keeping the reference to a commit thing keep as as a well know state), but I keep this conversation opened about switch to `yarn`, if there is still good reasons for the change.

**Comment by ndarilek** [comment]
Maybe Yarn didn't check to see whether the package names matched (I.e. I could have specified the dependency as `"foo": "https://..."` and Yarn might have pulled the repository directly, not caring whether the package name matched.) Not sure whether or not this is a good thing, but it blocked me from getting work done for a time, so take that for whatever it's worth. :)

There are other advantages to Yarn--significantly faster, nicer developer experience--but they're no longer showstoppers. I personally use Yarn for every Node project I start and maintain these days. NPM is certainly good enough, but it feels more and more like Yarn is eating its lunch these days. :)

**Comment by IagoSRL** [comment]
Actually, I'm thinking is better any package manager double checks the name (is less error prone), but noticing an error when didn't match (no one managed that correctly).

Should say that my error was to point out to a git branch (whose content can change from install to install) rather than a commit.

Version 5 of npm gets enhancements trying to match Yarn (lock file, speed) but don't know how much real difference exists still (Yarn seems faster still). Aside that, *seems* that Yarn uses more disk space according to [this article pro Yarn](https://www.keycdn.com/blog/npm-vs-yarn/); hope that doesn't means it doesn't dedupe by default and don't have flat mode (by default, autodetected), because that things do prevent some errors in Windows about long paths :-/

There is even more package managers claiming being better than npm and Yarn, [pnpm](https://pnpm.js.org/), [Turbo](https://medium.com/@ericsimons/introducing-turbo-5x-faster-than-yarn-npm-and-runs-natively-in-browser-cc2c39715403). Arghh.... JavaScript fatigue!

----------

I found the management of npm package-lock.json file a mess: it gets updated nearly on every install, creates differences when using different systems, so no sure if is doing what's expected. If Yarn manages it's lock file without this problems while having real benefits (deterministic installs), I will switch to it.

**Comment by IagoSRL** [comment]
I give a read to Yarn docs, and will give it a try and we will see if fixes the 'package-lock.json continues updates nonsense' :-)
Needed by current set-up of Travis, too.

In my local still: I fixed a conflict, actually reverting the reference to the grunt-contrib-uglify-es module (using a specific commit and the new name, I know now that's the best way --pointing to the branch could have unexpected updates).

Yarn in my computer, run against master is giving me warnings and errors that didn't happens with npm:
```
$ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "C:\\Users\\srlia\\AppData\\Local\\Yarn\\cache\\v1\\npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922c
e6b426411" as pattern ["esprima-fb@3001.1.0-dev-harmony-fb","esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in a non deterministic behavior, skipping.
error bliss@1.0.1: The engine "node" is incompatible with this module. Expected version ">= 0.5.0 < 0.7.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ndarilek** [comment]
Yarn isn't needed for Travis anymore. There are other issues with the 
Travis config that I didn't catch because it wasn't being actively 
built. Nothing major, mostly related to the Node app not being at the 
repository root, and I have to research how to point it at the app/ 
directory for package.json.

The Yarn issues are because you need the --ignore-engines flag to `yarn 
install`. The PR updates the quickstart docs as well. I may have the 
flag misremembered, but I'm pretty sure the docs are accurate.

**Comment by IagoSRL** [comment]
Thanks @ndarilek!
Yes, docs has the --ignore-engines flag, just followed Yarn docs since I was giving it a read.
Installs correctly with that comment.

My new question is, Is it a good practice to require use ever a non default flag?
I looked at the Bliss package and published version has the Node version restriction, while latest state at master has removed it. Tempted to point to git rather than version for this (anyway, there is a lot it doesn't updates this module).

**Comment by IagoSRL** [comment]
About Travis, maybe adding a `cd ./app` to one of that commands they allow as before_install, before_build they allow? (just thinking out loud)

**Comment by IagoSRL** [comment]
I still get a warning with Yarn (same about esprima-fb) but continuing. For some reason, running it on my computer updated the yarn.lock file again, it seems will behave same as npm5 by updating the file every time just because of different platforms are in use :-/

Anyway, merging

**Comment by ndarilek** [comment]
I think the "engines" field is treated more like advice rather than a 
hard requirement.

I assume both NPM and Yarn are using the same version of this package. 
If that is the case, then my secondary assumption is that NPM is quietly 
swallowing the error while Yarn is at least flatting it. So I don't know 
if the flag's use matters in terms of stability, but the fact that Yarn 
errors while NPM either warns or silently skips is interesting.

**Comment by IagoSRL** [comment]
Yes, another different behavior.. in this case prefer being noticed, but as you said should be a warning not an error; Yarn is closer to the best behavior here.

Updating package.json to point to a git commit for the bliss package so we prevent the engine problem (and because actually is compatible with latest Node versions).

I merged this right now, fixing the conflicts.

**Pull request merged**
