### PR TITLE
Is461 Revise /upgrade to become reusable

### PR DESCRIPTION
**Pull request by joshdanielson**
#461
- payment plans now can be reused
- style changes to payment plans

### CODE REVIEW

**Comment by IagoSRL** [comment]
The class `IconListCard` don't look like a card anymore, that's expected?

screen shot 2017-05-29 at 13 27 13

**Comment by IagoSRL** [comment]
The file app\source\js\appmodel\AppModel.paymentPlans.js was not updated with the new classes/html scheme for each payment plan description.
Anyway, is preferred we use the html templates/parts (shared code) rather than the html-in-js there, son can be refactored that way.

**Comment by joshdanielson** [comment]
@IagoSRL good catches! Sorry about the naming conventions...I will learn.

I added back the css for the IconListCard so it can be used like before and created a new class PaymentPlanBenefits (since it's not really a card). 

Yes, I don't know how to use the /parts in .js files so if you could work those in (fine if it's a separate issue), that would be great.

**Comment by IagoSRL** [comment]
Oops!  Merging the PR for #444 merged this automatically too...because the other one was based on this. I understand now why some of the diff changes sounded to me. Well is done, I still will keep #461 opened to fix the latest detail, integrating the plans html inside javascript.

**Pull request merged**
